"""Tier-3 probe: can a digit transformer learn MULTIPLY-THEN-REDUCE (a*b mod p)?

Go/no-go gate for the tier-3 bet (see TIER3_STRATEGY.md). The tier-0 probe showed
abacus transformers learn multiplication and generalise across values. Tier 3 adds
the hard part: modular reduction of the product by p. We give the model a
SCRATCHPAD — it emits the full product first, then the remainder — decomposing the
task into multiply (proven learnable in tier-0) followed by reduce (long-division-
like). Every digit is generated by the network (no Python ``%`` on the product), so
this stays submission-compliant; the only blessed Python reduction is on the
operands a, b, which are already in [0, p).

Sequence:  BOS a_lsb MUL b_lsb MOD p_lsb EQ  prod_lsb SEP rem_lsb EOS
Loss is on the scratchpad region only (product + SEP + remainder + EOS).

Eval: greedy-decode from "...EQ", parse the digits after SEP as the remainder, and
compare to the true (a*b) % p. We bucket by prime size to see how reduction scales
with p — the key question for whether tier 3 is reachable.

Curriculum (default on): ramp the prime ceiling from small primes up to the full
tier-3 range over the first ``--curr-frac`` of training, so the model learns
reduction where it's easy (few-digit p) before facing 5-digit primes. Division is
the hardest of the four operations for transformers; the curriculum is what makes
it tractable.

Usage:
    python training/tier3_probe.py --curriculum --steps 60000 --eval-every 2000
"""

from __future__ import annotations

import argparse
import bisect
import random
import time

import torch
import torch.nn as nn

from data import primes_for_tier

# Vocab: 0-9 digits, then specials.
PAD, BOS, MUL, MOD, EQ, SEP, EOS = 10, 11, 12, 13, 14, 15, 16
VOCAB = 17


def digits_lsb(n: int) -> list[int]:
    """Non-negative int -> decimal digits, least-significant-first ([0] for 0)."""
    if n == 0:
        return [0]
    out = []
    while n > 0:
        out.append(n % 10)
        n //= 10
    return out


def lsb_to_int(ds: list[int]) -> int:
    """Inverse of digits_lsb (digit list LSB-first -> int)."""
    v = 0
    for d in reversed(ds):
        v = v * 10 + d
    return v


def pick_device() -> torch.device:
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


# ---------------------------------------------------------------------------
# Example construction
# ---------------------------------------------------------------------------

def build_example(a: int, b: int, p: int, max_len: int):
    """Return (tokens, abacus_idx, is_output) padded to max_len.

    The scratchpad target is the product then the remainder; only those (plus the
    SEP and final EOS) are supervised.
    """
    prod, rem = a * b, (a * b) % p
    ar, br, pr = digits_lsb(a), digits_lsb(b), digits_lsb(p)
    prodr, remr = digits_lsb(prod), digits_lsb(rem)
    toks = [BOS] + ar + [MUL] + br + [MOD] + pr + [EQ] + prodr + [SEP] + remr + [EOS]
    # Abacus index = position within the current number (resets each segment;
    # specials get 0).
    abac = (
        [0] + list(range(len(ar))) + [0] + list(range(len(br)))
        + [0] + list(range(len(pr))) + [0] + list(range(len(prodr)))
        + [0] + list(range(len(remr))) + [0]
    )
    # Supervise the scratchpad: product digits, SEP, remainder digits, EOS.
    is_out = (
        [False] + [False] * len(ar) + [False] + [False] * len(br)
        + [False] + [False] * len(pr) + [False] + [True] * len(prodr)
        + [True] + [True] * len(remr) + [True]
    )
    pad = max_len - len(toks)
    if pad < 0:
        raise ValueError(f"max_len {max_len} too small for sequence of {len(toks)}")
    toks += [PAD] * pad
    abac += [0] * pad
    is_out += [False] * pad
    return toks, abac, is_out


def make_batch(batch: int, primes: list[int], max_len: int, rng, device):
    """Sample (a, b) uniform residues for primes drawn from the current pool."""
    T, A, M = [], [], []
    for _ in range(batch):
        p = primes[rng.randrange(len(primes))]
        a, b = rng.randrange(p), rng.randrange(p)
        t, ab, m = build_example(a, b, p, max_len)
        T.append(t); A.append(ab); M.append(m)
    tt = lambda v, dt: torch.tensor(v, dtype=dt, device=device)
    return tt(T, torch.long), tt(A, torch.long), tt(M, torch.bool)


# ---------------------------------------------------------------------------
# Model (same abacus decoder as the tier-0 probe, wider vocab)
# ---------------------------------------------------------------------------

class AbacusDecoder(nn.Module):
    def __init__(self, max_len: int, abacus_max: int, d_model=256, nhead=8,
                 num_layers=6, dim_ff=1024):
        super().__init__()
        self.tok_emb = nn.Embedding(VOCAB, d_model)
        self.pos_emb = nn.Embedding(max_len, d_model)          # absolute position
        self.abacus_emb = nn.Embedding(abacus_max, d_model)    # place within number
        layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=nhead, dim_feedforward=dim_ff,
            dropout=0.0, batch_first=True, activation="gelu",
        )
        self.transformer = nn.TransformerEncoder(layer, num_layers=num_layers)
        self.ln = nn.LayerNorm(d_model)
        self.head = nn.Linear(d_model, VOCAB, bias=False)
        self.max_len = max_len
        self.register_buffer("pos_ids", torch.arange(max_len), persistent=False)

    def forward(self, toks, abacus):
        b, t = toks.shape
        x = self.tok_emb(toks) + self.pos_emb(self.pos_ids[:t]) + self.abacus_emb(abacus)
        mask = torch.triu(torch.full((t, t), float("-inf"), device=toks.device), diagonal=1)
        x = self.transformer(x, mask=mask, is_causal=True)
        return self.head(self.ln(x))


# ---------------------------------------------------------------------------
# Eval: autoregressive greedy decode of scratchpad, exact-match on the remainder
# ---------------------------------------------------------------------------

@torch.no_grad()
def eval_remainder(model, primes, n, max_len, abacus_max, rng, device):
    """Returns (rem_exact, prod_exact) over n freshly-sampled pairs on `primes`."""
    model.eval()
    rem_ok = prod_ok = 0
    for _ in range(n):
        p = primes[rng.randrange(len(primes))]
        a, b = rng.randrange(p), rng.randrange(p)
        true_prod, true_rem = a * b, (a * b) % p
        ar, br, pr = digits_lsb(a), digits_lsb(b), digits_lsb(p)
        toks = [BOS] + ar + [MUL] + br + [MOD] + pr + [EQ]
        abac = ([0] + list(range(len(ar))) + [0] + list(range(len(br)))
                + [0] + list(range(len(pr))) + [0])
        gen, seg = [], 0  # seg = place index within the current generated number
        while len(toks) < max_len:
            tt = torch.tensor([toks], dtype=torch.long, device=device)
            aa = torch.tensor([abac], dtype=torch.long, device=device)
            nxt = int(model(tt, aa)[0, -1].argmax())
            if nxt == EOS:
                break
            toks.append(nxt); gen.append(nxt)
            if nxt == SEP:
                abac.append(0); seg = 0          # reset place index after SEP
            else:
                abac.append(min(seg, abacus_max - 1)); seg += 1
        # Split the scratchpad at SEP: product digits, then remainder digits.
        if SEP in gen:
            k = gen.index(SEP)
            prod_ds = [d for d in gen[:k] if d < 10]
            rem_ds = [d for d in gen[k + 1:] if d < 10]
        else:
            prod_ds = [d for d in gen if d < 10]
            rem_ds = []
        if rem_ds and lsb_to_int(rem_ds) == true_rem:
            rem_ok += 1
        if prod_ds and lsb_to_int(prod_ds) == true_prod:
            prod_ok += 1
    return rem_ok / n, prod_ok / n


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--steps", type=int, default=60000)
    ap.add_argument("--batch", type=int, default=256)
    ap.add_argument("--lr", type=float, default=3e-4)
    ap.add_argument("--d-model", type=int, default=256)
    ap.add_argument("--layers", type=int, default=6)
    ap.add_argument("--nhead", type=int, default=8)
    ap.add_argument("--dim-ff", type=int, default=1024)
    ap.add_argument("--eval-every", type=int, default=2000)
    ap.add_argument("--eval-n", type=int, default=300, help="samples per size-bucket at eval")
    ap.add_argument("--p-min", type=int, default=512)
    ap.add_argument("--p-max", type=int, default=65536)
    ap.add_argument("--curriculum", action="store_true",
                    help="ramp the prime ceiling small->large over --curr-frac of training")
    ap.add_argument("--curr-frac", type=float, default=0.6)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    torch.manual_seed(args.seed)
    device = pick_device()
    rng = random.Random(args.seed)
    eval_rng = random.Random(999)

    # Full sorted tier-3 prime pool, clipped to [p_min, p_max).
    POOL = [p for p in primes_for_tier(3) if args.p_min <= p < args.p_max]
    if not POOL:
        raise SystemExit(f"no primes in [{args.p_min}, {args.p_max})")

    maxd = len(str(args.p_max - 1))            # digits in the largest prime (~5)
    max_len = 4 * maxd + 16                     # BOS a MUL b MOD p EQ prod SEP rem EOS
    abacus_max = 2 * maxd + 2                   # product has up to 2*maxd digits

    # Curriculum: geometric ramp of the prime ceiling.
    curr_start = min(max(args.p_min * 4, 1024), args.p_max)

    def cur_pmax(step: int) -> int:
        if not args.curriculum:
            return args.p_max
        frac = min(1.0, step / max(1, args.curr_frac * args.steps))
        return int(curr_start * (args.p_max / curr_start) ** frac)

    # Eval size-buckets to watch how reduction scales with p.
    edges = [(512, 2048), (2048, 8192), (8192, 65536)]
    buckets = []
    for lo, hi in edges:
        lo2, hi2 = max(lo, args.p_min), min(hi, args.p_max)
        if lo2 < hi2:
            ps = [p for p in POOL if lo2 <= p < hi2]
            if ps:
                buckets.append((lo2, hi2, ps))

    model = AbacusDecoder(max_len, abacus_max, d_model=args.d_model, nhead=args.nhead,
                          num_layers=args.layers, dim_ff=args.dim_ff).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"device {device} | pool {len(POOL)} primes [{args.p_min},{args.p_max}) | "
          f"max_len {max_len} | curriculum {args.curriculum} | params {n_params:,}")

    opt = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=0.01)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.steps, eta_min=args.lr * 0.1)
    loss_fn = nn.CrossEntropyLoss()
    start = time.monotonic()

    for step in range(1, args.steps + 1):
        model.train()
        # Restrict to the current curriculum ceiling.
        hi = bisect.bisect_left(POOL, cur_pmax(step))
        primes_now = POOL[:hi] if hi > 0 else POOL[:1]
        toks, abac, mask = make_batch(args.batch, primes_now, max_len, rng, device)
        logits = model(toks, abac)
        logits = logits[:, :-1].reshape(-1, VOCAB)     # predict token t+1 from t
        target = toks[:, 1:].reshape(-1)
        m = mask[:, 1:].reshape(-1)                    # supervise scratchpad only
        loss = loss_fn(logits[m], target[m])
        opt.zero_grad(); loss.backward(); opt.step(); sched.step()

        if step % args.eval_every == 0:
            parts = []
            for lo, hi, ps in buckets:
                rem, prod = eval_remainder(model, ps, args.eval_n, max_len,
                                           abacus_max, eval_rng, device)
                parts.append(f"[{lo}-{hi}) rem {rem:.3f} prod {prod:.3f}")
            print(f"step {step:6d} | loss {loss.item():.4f} | " + " | ".join(parts)
                  + f" | cur_pmax {cur_pmax(step)} | {time.monotonic()-start:.0f}s")

    print("done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
